# config.yaml
dataset:
  download_dir: "data"
  images_zip_url: "https://github.com/jbrownlee/Datasets/releases/download/Flickr8k/Flickr8k_Dataset.zip"
  captions_url: "https://github.com/jbrownlee/Datasets/releases/download/Flickr8k/Flickr8k_text.zip"
  images_zip_name: "Flickr8k_Dataset.zip"
  captions_zip_name: "Flickr8k_text.zip"
  captions_file_name: "Flickr8k.token.txt"
  train_images_file: "Flickr_8k.trainImages.txt"
  dev_images_file: "Flickr_8k.devImages.txt"
  test_images_file: "Flickr_8k.testImages.txt"
  images_dir: "data/Flicker8k_Dataset"
  caption_path: "data/captions.txt"

validation:
  dataset_base_dir: "data/"
  images_dir: "data/Flicker8k_Dataset"
  captions_file: "data/captions.txt"
  validation_report_file: "reports/data_validation_report.json"
  image_extensions:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".bmp"
    - ".tiff"
    - ".gif"

create_dataset:
  dataset_base_dir: "data/"
  train_images_file: "Flickr_8k.trainImages.txt"
  dev_images_file: "Flickr_8k.devImages.txt"
  test_images_file: "Flickr_8k.testImages.txt"
  images_dir: "data/Flicker8k_Dataset"
  caption_path: "data/captions.txt"

training:
  model_dir: "artifacts/models"
  model_name: "transformer_captioning_model.pth"
  report_dir: "artifacts/reports"
  model_save_prefix: "transformer_caption_model"

inference:
  model_path: "artifacts/models/transformer_caption_model_best_model.pth"
  report_dir: "artifacts/reports/"
